import track from "../models/track"

export default class loader {
    static trackList() {
        return [
            new track('ambient loop 1', 'THTF ambient loop 1.flac'),
            new track('ambient loop 2', 'THTF ambient loop 2.flac'),
            new track('bass 1', 'THTF bass ch 1.flac'),
            new track('bass loop 2', 'THTF bass END loop.flac'),
            new track('bass loop 3', 'THTF bass verse loop 1.flac'),
            new track('BV 1', 'THTF BV 1.flac'),
            new track('BV 2', 'THTF BV 2.flac'),
            new track('BV 3', 'THTF BV 3.flac'),
            new track('BV 4', 'THTF BV 4.flac'),
            new track('coco loop 1', 'THTF coco loop 1.flac'),
            new track('coco loop 2', 'THTF coco loop 2.flac'),
            new track('coco loop 3', 'THTF coco loop 3.flac'),
            new track('coco puff loop', 'THTF coco puff loop 1.flac'),
            new track('mid perc 1', 'THTF DDL mid perc 2.flac'),
            new track('mid perc 2', 'THTF DDL mid perc 3.flac'),
            new track('drum fill', 'THTF drum fill 2.flac'),
            new track('drum loop 1', 'THTF drum loop 1.flac'),
            new track('drum loop 2', 'THTF drum loop 2.flac'),
            new track('drum loop 3', 'THTF drum loop 4.flac'),
            new track('drum loop 4', 'THTF drum loop 5.flac'),
            new track('drum loop 5', 'THTF drum loop 6.flac'),
            new track('drum loop 6', 'THTF drum loop 7.flac'),
            new track('drum loop 7', 'THTF drum loop 8.flac'),
            new track('drum mid 1', 'THTF drum MID 1.flac'),
            new track('drum mid 2', 'THTF drum MID 2.flac'),
            new track('drum mid 3', 'THTF drum MID 3.flac'),
            new track('end drum loop', 'THTF end drum loop.flac'),
            new track('synth riff', 'THTF end synth riff.flac'),
            new track('intro', 'THTF filtered intro.flac'),
            new track('guitar ch riff 1', 'THTF GTR ch riff 1.flac'),
            new track('guitar ch riff 2', 'THTF GTR CH riff 2.flac'),
            new track('guitar riff 1', 'THTF gtr riff 1.flac'),
            new track('guitar riff 2', 'THTF gtr riff 2.flac'),
            new track('guitar riff 3', 'THTF GTR riff 3.flac'),
            new track('hat loop 1', 'THTF hat loop 1.flac'),
            new track('hat loop 2', 'THTF hat loop 2.flac'),
            new track('hat loop 3', 'THTF hat loop 4.flac'),
            new track('hat loop end 1', 'THTF hat loop end 1.flac'),
            new track('hat loop end 2', 'THTF hat loop end 2.flac'),
            new track('hat loop fill', 'THTF hat loop fill.flac'),
            new track('hat loop tail', 'THTF hat loop tail.flac'),
            new track('intro', 'THTF intro.flac'),
            new track('ddl perc 1', 'THTF mid DDL perc 1.flac'),
            new track('mod synth riff', 'THTF mod synth riff.flac'),
            new track('perc loop 1', 'THTF perc loop 1.flac'),
            new track('synth riff 1', 'THTF synth riff 1.flac'),
            new track('synth riff 2', 'THTF synth riff 2.flac'),
            new track('synth riff 3', 'THTF synth riff 3.flac'),
            new track('synth perc 1', 'THTF synth-perc 1.flac'),
            new track('tom pattern 1', 'THTF tom pattern 1.flac'),
            new track('tom pattern 2', 'THTF tom pattern 2.flac'),
            new track('virus seq', 'THTF Virus seq.flac')
        ]
    }
}