import track from "../models/track"

export default class loader {
    static trackList() {
        return [
            new track('ambient loop 1', '/assets/audio/THTF ambient loop 1.flac'),
            new track('ambient loop 2', '/assets/audio/THTF ambient loop 2.flac'),
            new track('bass 1', '/assets/audio/THTF bass ch 1.flac'),
            new track('bass loop 2', '/assets/audio/THTF bass END loop.flac'),
            new track('bass loop 3', '/assets/audio/THTF bass verse loop 1.flac'),
            new track('BV 1', '/assets/audio/THTF BV 1.flac'),
            new track('BV 2', '/assets/audio/THTF BV 2.flac'),
            new track('BV 3', '/assets/audio/THTF BV 3.flac'),
            new track('BV 4', '/assets/audio/THTF BV 4.flac'),
            new track('coco loop 1', '/assets/audio/THTF coco loop 1.flac'),
            new track('coco loop 2', '/assets/audio/THTF coco loop 2.flac'),
            new track('coco loop 3', '/assets/audio/THTF coco loop 3.flac'),
            new track('coco puff loop', '/assets/audio/THTF coco puff loop 1.flac'),
            new track('mid perc 1', '/assets/audio/THTF DDL mid perc 2.flac'),
            new track('mid perc 2', '/assets/audio/THTF DDL mid perc 3.flac'),
            new track('drum fill', '/assets/audio/THTF drum fill 2.flac'),
            new track('drum loop 1', '/assets/audio/THTF drum loop 1.flac'),
            new track('drum loop 2', '/assets/audio/THTF drum loop 2.flac'),
            new track('drum loop 3', '/assets/audio/THTF drum loop 4.flac'),
            new track('drum loop 4', '/assets/audio/THTF drum loop 5.flac'),
            new track('drum loop 5', '/assets/audio/THTF drum loop 6.flac'),
            new track('drum loop 6', '/assets/audio/THTF drum loop 7.flac'),
            new track('drum loop 7', '/assets/audio/THTF drum loop 8.flac'),
            new track('drum mid 1', '/assets/audio/THTF drum MID 1.flac'),
            new track('drum mid 2', '/assets/audio/THTF drum MID 2.flac'),
            new track('drum mid 3', '/assets/audio/THTF drum MID 3.flac'),
            new track('end drum loop', '/assets/audio/THTF end drum loop.flac'),
            new track('synth riff', '/assets/audio/THTF end synth riff.flac'),
            new track('intro', '/assets/audio/THTF filtered intro.flac'),
            new track('guitar ch riff 1', '/assets/audio/THTF GTR ch riff 1.flac'),
            new track('guitar ch riff 2', '/assets/audio/THTF GTR CH riff 2.flac'),
            new track('guitar riff 1', '/assets/audio/THTF gtr riff 1.flac'),
            new track('guitar riff 2', '/assets/audio/THTF gtr riff 2.flac'),
            new track('guitar riff 3', '/assets/audio/THTF GTR riff 3.flac'),
            new track('hat loop 1', '/assets/audio/THTF hat loop 1.flac'),
            new track('hat loop 2', '/assets/audio/THTF hat loop 2.flac'),
            new track('hat loop 3', '/assets/audio/THTF hat loop 4.flac'),
            new track('hat loop end 1', '/assets/audio/THTF hat loop end 1.flac'),
            new track('hat loop end 2', '/assets/audio/THTF hat loop end 2.flac'),
            new track('hat loop fill', '/assets/audio/THTF hat loop fill.flac'),
            new track('hat loop tail', '/assets/audio/THTF hat loop tail.flac'),
            new track('intro', '/assets/audio/THTF intro.flac'),
            new track('ddl perc 1', '/assets/audio/THTF mid DDL perc 1.flac'),
            new track('mod synth riff', '/assets/audio/THTF mod synth riff.flac'),
            new track('perc loop 1', '/assets/audio/THTF perc loop 1.flac'),
            new track('synth riff 1', '/assets/audio/THTF synth riff 1.flac'),
            new track('synth riff 2', '/assets/audio/THTF synth riff 2.flac'),
            new track('synth riff 3', '/assets/audio/THTF synth riff 3.flac'),
            new track('synth perc 1', '/assets/audio/THTF synth-perc 1.flac'),
            new track('tom pattern 1', '/assets/audio/THTF tom pattern 1.flac'),
            new track('tom pattern 2', '/assets/audio/THTF tom pattern 2.flac'),
            new track('virus seq', '/assets/audio/THTF Virus seq.flac')
        ]
    }
}